### ISSUE TITLE
The mod Crashes during a Smith!

### ISSUE THREAD

**Issue by DoomShin** [Rajhab/More-Vanilla-Shields-Forge#1]
During a Smith, The mod Crashed!
For example, Netherite upgrade makes a Crash...

**Comment by Rajhab** [comment]
@DoomShin Hey. Can you send me the crash log? It is found in your .minecraft folder in the crashes folder. I have tested it yesterday and didnt have any crashes. Do you have any other mods?

**Comment by DoomShin** [comment]
Sorry! It was other mod's Crash. The mod was Enderite CJ... And It's fixed now.

**Comment by Rajhab** [comment]
> Sorry! It was other mod's Crash. The mod was Enderite CJ... And It's fixed now.
> 

Perfect. You have a nice day!
