### ISSUE TITLE
[1.20.1 Fabric] Server Crashes when using More Vanilla Shields

### ISSUE THREAD

**Issue by MrElectrum** [Rajhab/More-Vanilla-Shields-Forge#2]
I've been building a modpack and I wanted to add extra shields that were compatible with some of the other enchantment mods, and this one was the only one that seemed to work in testing. I went to go add it to the server side, and I got an error:

![image](https://github.com/Rajhab/More-Vanilla-Shields-Forge/assets/172245912/5c3e6734-9e12-4db4-9315-2479a1f4b644)

It seemed to work fine in single player, but I just can't start the server if I have this mod installed.

**Comment by Rajhab** [comment]
Hey @MrElectrum . Sorry for the error. Let me just test it real quick and i come back to you.

**Comment by Rajhab** [comment]
> I've been building a modpack and I wanted to add extra shields that were compatible with some of the other enchantment mods, and this one was the only one that seemed to work in testing. I went to go add it to the server side, and I got an error:
> 
> ![image](https://private-user-images.githubusercontent.com/172245912/343309707-5c3e6734-9e12-4db4-9315-2479a1f4b644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzQ5NTMsIm5iZiI6MTcxOTQzNDY1MywicGF0aCI6Ii8xNzIyNDU5MTIvMzQzMzA5NzA3LTVjM2U2NzM0LTllMTItNGRiNC05MzE1LTI0NzlhMWY0YjY0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMDQ0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWEwNjFjNjc4NjYxODNmMzYyZjYzZGQ3N2NmY2YzN2MwNzIwOWY3MzQwNWM4MmM5OTNlYzE3ZWJkMTA4NDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mO3AbJRMBE7bo_GzofQj8NORqqsh06F_Xb_F-l3aBBU)
> 
> It seemed to work fine in single player, but I just can't start the server if I have this mod installed.

Yes you're right. It crashes... That is not good. Gonna fix that as soon as possible! Thanks for submitting your error!
Gonna tag you in a new comment when it is fixed!

**Comment by Rajhab** [comment]
@MrElectrum thanks again for reporting this heavy error. Got it fixed. This is the new Version for 1.20.1-fabric. It will be released officially tomorrow evening in german time zone. You get now an exclusive version for the quick fix. 

[morevanillashields-1.0.2-1.20.1-fabric](
https://cdn.discordapp.com/attachments/1187337588210679860/1255632034530070568/morevanillashields-1.0.2-1.20.1.jar?ex=667dd5f5&is=667c8475&hm=a84ca7b9753992b97f5e53f4d09f5baf640048071ca307d02765cd4bbe72bfb1&)

Hope that download link functions like butter. If not please don't hesitate to message me again.

Thanks again and you have a nice day! <3

**Comment by MrElectrum** [comment]
> @MrElectrum thanks again for reporting this heavy error. Got it fixed. This is the new Version for 1.20.1-fabric. It will be released officially tomorrow evening in german time zone. You get now an exclusive version for the quick fix.
> 
> [morevanillashields-1.0.2-1.20.1-fabric](https://cdn.discordapp.com/attachments/1187337588210679860/1255632034530070568/morevanillashields-1.0.2-1.20.1.jar?ex=667dd5f5&is=667c8475&hm=a84ca7b9753992b97f5e53f4d09f5baf640048071ca307d02765cd4bbe72bfb1&)
> 
> Hope that download link functions like butter. If not please don't hesitate to message me again.
> 
> Thanks again and you have a nice day! <3

No problem mate! It works perfectly now!!

![image](https://github.com/Rajhab/More-Vanilla-Shields-Forge/assets/172245912/135e03a4-a3c4-4802-8a3a-79f59b60880d)

Thanks for the great mod! Have a good one!
