### ISSUE TITLE
can you support forge version 47.3.1？

### ISSUE THREAD

**Issue by NeoStarWonV** [Rajhab/More-Vanilla-Shields-Forge#5]
I cant upgrade my forge version out of some reasons.But I really love you shield mod

**Comment by Rajhab** [comment]
> I cant upgrade my forge version out of some reasons.But I really love you shield mod

Hey there. Thank you! But what do you mean you cant update? 1.20.1 forge supports every version of my mod. Do you have any screenshots?

**Comment by NeoStarWonV** [comment]
My modpack has so many mods. The majority of them  work on forge with the version 47.3.1 well instead of above 47.3.1
![image](https://github.com/user-attachments/assets/7fd4bbcd-058d-48e5-949a-311f2137ac44)
 cant play it because my forge version is 47.3.1

**Comment by NeoStarWonV** [comment]
A few days ago,I dont know if you permit it.I noticed that the forge version of your source of 1.1.1 is 47.3.5.I downloaded it and tried to transform it into 47.3.1.After I build the source,I successfully let it working on my game.But as the latest version 1.1.3,it doesn't work as a similar approach.So I want to ask you make it compatible with 47.3.1

**Comment by Rajhab** [comment]
> A few days ago,I dont know if you permit it.I noticed that the forge version of your source of 1.1.1 is 47.3.5.I downloaded it and tried to transform it into 47.3.1.After I build the source,I successfully let it working on my game.But as the latest version 1.1.3,it doesn't work as a similar approach.So I want to ask you make it compatible with 47.3.1
>  

Hey. No problem. Next version (coming in the few days) will be compatible with some of the older forge build versions. But can I ask why you won't update to 43.1.10?

Best regards
Rajhab <3

**Comment by NeoStarWonV** [comment]
My mod pack has over 500 mods.part of them not support the higer forge version and the crash log can't tell me the specific mod who it is

**Comment by Rajhab** [comment]
> My mod pack has over 500 mods.part of them not support the higer forge version and the crash log can't tell me the specific mod who it is

Okok good to now. Gonna pin you in this issue when the new version is released!

Thanks again for the report!

**Comment by NeoStarWonV** [comment]
> > My mod pack has over 500 mods.part of them not support the higer forge version and the crash log can't tell me the specific mod who it is
> 
> Okok good to now. Gonna pin you in this issue when the new version is released!
> 
> Thanks again for the report!

OK,thank you

**Comment by Rajhab** [comment]
Hey @NeoStarWonV . New Version is released. Should work now perfectly fine with 47.3.1.

Thanks and have fun!

**Comment by NeoStarWonV** [comment]
Oh,Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!Thanks!
